{
 "title": "CIS Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cis_benchmark_result,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top CIS Warning Developer",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(desc) (cis_benchmark_result{instance=~\"$instance\", id=~\"[4-5].+|7.4+\", id!~\"4.5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top CIS Warning DevOps",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(desc) (cis_benchmark_result{instance=~\"$instance\", id=~\"[1-3].+|[6-7].+\", id!~\"7.4|7.1|7.6\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Node Base CIS Warning",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (cis_benchmark_result{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CIS Warning",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cis_benchmark_result{instance=~\"$instance\", result=\"WARN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Developer Base CIS Warning - Details",
   "type": "timeseries",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "cis_benchmark_result{id=~\"[4-5].+|7.4+\", id!~\"4.5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cis_benchmark_result{id=~\"[4-5].+|7.4+\", id!~\"4.5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DevOps Base CIS Warning - Details",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "cis_benchmark_result{id=~\"[1-3].+|[6-7].+\", id!~\"7.4|7.1|7.6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cis_benchmark_result{id=~\"[1-3].+|[6-7].+\", id!~\"7.4|7.1|7.6\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}